version: "3.7"
services:
  node:
    build: ./
    container_name: node_app
    image: node-docker:v1
    volumes:
      - ./app/:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
volumes:
  node_modules: {}