name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker login -u wsmathias9 --password ${{ secrets.TMP }}
        tag=$(date +%s)
        docker build . --file Dockerfile --tag wsmathias9/node-dev:$tag
        docker push wsmathias9/node-dev:$tag
